### ISSUE TITLE
Error popup on Dialog color picker selection in Magnolia DX Core 6.2.3

### ISSUE THREAD

**Issue by NiclasHorstad-acn** [magnolia-community/color-picker-field#2]
The color picker (1.1) is installed on Magnolia DX Core 6.2.3 and works just as expected.

However, the following error appears every time the color picker window is opened in the dialog:
```
The UI contains modal windows, non-modal window cannot be brought to front.
RpcInvocationException: Unable to invoke method openPopup in com.vaadin.shared.ui.colorpicker.ColorPickerServerRpc caused by InvocationTargetException caused by IllegalStateException: The UI contains modal windows, non-modal window cannot be brought to front.
```

A workaround could be to suppress this warning, but it is not ideal. Is this a known issue?

**Comment by rgange** [comment]
No it's not known but I will look into it. Thanks for letting me know.

**Comment by rgange** [comment]
Related to https://github.com/vaadin/framework/issues/9511

**Comment by rgange** [comment]
Fixed by setting modal to true. https://github.com/magnolia-community/color-picker-field/commit/26560892f2c873ac8b3e1fd8f91ed40963b6aa16
